### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory - parsing {%- Syntax in a liquid

### ISSUE THREAD

**Issue by bastifantasti** [Potherca/liquid-linter-cli#7]
## Problem/Motivation

> When the CLI parses a liquid including a html-stripped liquid tag {%- the Package crashes complete after it filled up the Node Memory
## Expected behaviour

> the liquid will be parsed

## Actual behaviour

> the module crashes after the Node Memory runs full

## Steps to reproduce

> add something like this in your code: {%- for item in order.line_items -%}

**Comment by Potherca** [comment]
Hi! Thank you for taking the time to report this.

We are in the middle of migrating active development of this package to https://github.com/UnicornGlobal/liquid-linter-cli, this repo is about to be archived. Could you open this issue over at UnicornGlobal?
